
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('courses').del()
    .then(function () {
      // Inserts seed entries
      return knex('courses').insert([
        {
          ranking: 1,
          name: "Royal County Down G.C.",
          image: "../courseAerials/1_RoyalCountyDown.jpg",
          yearFounded: 1889,
          privatOrPublic: "Private/Public",
          city: "Newcastle",
          stateOrProvince: "County Down",
          country: "Northern Ireland",
          architects: [
            "Old Tom Morris",
          ],
          yards: 7186,
          par: 71,
          lat: 54.216937,
          lng: -5.885974,
          description: "On a clear spring day, with Dundrum Bay to the east, the Mountains of Mourne to the south and gorse-covered dunes in golden bloom, there is no lovelier place in golf than our new No. 1. Its design is attributed to Old Tom Morris but was refined by half a dozen architects in the past 120 years, most recently by Donald Steel. Though the greens are surprisingly flat, as if to compensate for the rugged terrain and numerous blind shots, bunkers are a definite highlight, most with arched eyebrows of dense marram grasses and impenetrable clumps of heather.",
        },
        {
          ranking: 2,
          name: "Augusta National G.C.",
          image: "../courseAerials/2_Augusta.jpg",
          yearFounded: 1933,
          privatOrPublic: "Private",
          city: "Augusta",
          stateOrProvince: "Georgia",
          country: "U.S.A.",
          architects: [
            "Bobby Jones",
            "Alister MacKenzie",
          ],
          yards: 7435,
          par: 72,
          lat: 33.5021365,
          lng: -82.0226276,
          description: "No club has tinkered with its golf course as often or as effectively over the decades as has Augusta National, mainly to keep it competitive for the annual Masters Tournament, an event it has conducted since 1934, with time off during WWII. All that tinkering has resulted in an amalgamation of design ideas, with a routing by Alister MacKenzie and Bob Jones, some Perry Maxwell greens, some Trent Jones water hazards, some Jack Nicklaus mounds and, in the last decade, extensive lengthening and rebunkering by Tom Fazio.",
        },
        {
          ranking: 3,
          name: "Pine Valley G.C.",
          image: "../courseAerials/3_PineValley.jpg",
          yearFounded: 1913,
          privatOrPublic: "Private",
          city: "Pine Valley",
          stateOrProvince: "New Jersey",
          country: "U.S.A.",
          architects: [
            "George Crump",
            "Harry Colt",
            "Charles Hugh Alison",
            "A. W. Tillinghast",
            "Perry Maxwell",
          ],
          yards: 7057,
          par: 70,
          lat: 39.7921578,
          lng: -74.9714701,
          description: "A genuine original, its unique character was forged from the sandy pine barrens of southwest Jersey. Founder George Crump had help from architects H.S. Colt, A.W. Tillinghast, George C. Thomas Jr. and Walter Travis. Hugh Wilson of Merion fame finished the job. Pine Valley blends all three schools of golf design – penal, heroic and strategic – throughout the course, often times on a single hole.",
        },
        {
          ranking: 4,
          name: "Cypress Point Club",
          image: "../courseAerials/4_CypressPoint.jpg",
          yearFounded: 1928,
          privatOrPublic: "Private",
          city: "Pebble Beach",
          stateOrProvince: "California",
          country: "U.S.A.",
          architects: [
            "Alister MacKenzie",
            "Robert Hunter",
          ],
          yards: 6524,
          par: 72,
          lat: 36.5802249,
          lng: -121.9741049,
          description: "Alister MacKenzie's masterpiece, woven through cypress, sand dunes and jagged coastline. In the 2000s, member Sandy Tatum, a former USGA president who christened Cypress Point as the Sistine Chapel of golf, convinced the club not to combat technology by adding new back tees, but instead make a statement by celebrating its original architecture. So Cypress remains timeless, if short, its charm helped in part by re-establishment of MacKenzie's fancy bunkering.",
        },
        {
          ranking: 5,
          name: "Royal Dornoch G.C.",
          image: "../courseAerials/5_RoyalDornoch.jpg",
          yearFounded: 1877,
          privatOrPublic: "Public",
          city: "Dornoch",
          stateOrProvince: "Sutherland",
          country: "Scotland",
          architects: [
            "Old Tom Morris",
          ],
          yards: 6704,
          par: 70,
          lat: 57.879296,
          lng: -4.023886,
          description: "Herbert Warren Wind called it the most natural course in the world. Tom Watson called it the most fun he'd had playing golf. Donald Ross called it his home, having been born in the village and learned the game on the links. Tucked in an arc of dunes along the North Sea shoreline, Dornoch's greens, some by Old Tom Morris, others by John Sutherland or tour pro George Duncan, sit mostly on plateaus and don't really favor bounce-and-run golf. That's the challenge. Hitting those greens in a Dornoch wind.",
        },
        {
          ranking: 6,
          name: "Royal Melbourne G.C. (West)",
          image: "../courseAerials/6_RoyalMelbourne.jpg",
          yearFounded: 1891,
          privatOrPublic: "Private",
          city: "Melbourne",
          stateOrProvince: "Victoria",
          country: "Australia",
          architects: [
            "Sir James McBain",
            "Alister MacKenzie",
          ],
          yards: 6643,
          par: 72,
          lat: -37.9678325,
          lng: 145.0253219,
          description: "Alister MacKenzie's 1926 routing fits snuggly into the contours of the rolling sandbelt land. His greens are miniature versions of the surrounding topography. His crisp bunkering, with vertical edges a foot or more tall, chew into fairways and putting surfaces. Most holes dogleg, so distance means nothing and angle into the pin is everything. For championships, holes 8 & 9 and 13 - 16 are skipped in favor of six from the East Course, which is ranked No. 55. That 'composite course' was once ranked by several publications.",
        },
        {
          ranking: 7,
          name: "Shinnecock Hills G.C.",
          image: "../courseAerials/7_Shinnecock.jpg",
          yearFounded: 1891,
          privatOrPublic: "Private",
          city: "Southampton",
          stateOrProvince: "New York",
          country: "U.S.A.",
          architects: [
            "William Flynn",
            "C.B. MacDonald",
            "Willie Dunn",
            "Willie Davis",
          ],
          yards: 7041,
          par: 70,
          lat: 40.896436,
          lng: -72.440609,
          description: "Generally considered to be the earliest links in America, heavily remodeled twice by C.B. Macdonald, then replaced (except for three holes) by William S. Flynn in the early 1930s. It's so sublime that its architecture hasn't really been fiddled with in nearly 50 years, although the team of Bill Coore and Ben Crenshaw have restored interesting features to prepare Shinnecock for the 2018 U.S. Open.",
        },
        {
          ranking: 8,
          name: "The Old Course at St. Andrews Links",
          image: "../courseAerials/8_StAndrews.jpg",
          yearFounded: 1552,
          privatOrPublic: "Private/Public",
          city: "St. Andrews",
          stateOrProvince: "Fife",
          country: "Scotland",
          architects: [
            "Old Tom Morris",
          ],
          yards: 7279,
          par: 72,
          lat: 56.3428104,
          lng: -2.802694,
          description: "The Old Course at St. Andrews is ground zero for all golf architecture. Every course designed since has either been in response to one or more of its features, or in reaction against it. Architects either favor the Old Course's blind shots or detest them, either embrace St. Andrews's enormous greens or consider them a waste of turf. Latest polarizing topic: Martin Hawtree's design changes in advance of the 2015 British Open. Many considered it blasphemy beforehand. After Zach Johnson's dramatic overtime victory, few mentioned the alterations.",
        },
        {
          ranking: 9,
          name: "Muirfield",
          image: "../courseAerials/9_Muirfield.jpg",
          yearFounded: 1891,
          privatOrPublic: "Private",
          city: "Gullane",
          stateOrProvince: "East Lothian",
          country: "Scotland",
          architects: [
            "Old Tom Morris",
          ],
          yards: 7209,
          par: 71,
          lat: 56.041578,
          lng: -2.8211708,
          description: "Muirfield is universally admired as a low-key, straightforward links with fairways seemingly containing a million traffic bumps. Except for a blind tee shot on the 11th, every shot is visible and well-defined. Greens are the correct size to fit the expected iron of approach. The routing changes direction on every hole to pose different wind conditions. The front runs clockwise, the back counterclockwise, but history mistakenly credits Old Tom Morris with Muirfield's returning nines. That was the result of H.S. Colt's 1925 redesign.",
        },
        {
          ranking: 10,
          name: "Merion G.C. (East)",
          image: "../courseAerials/10_Merion.jpg",
          yearFounded: 1912,
          privatOrPublic: "Private",
          city: "Ardmore",
          stateOrProvince: "Pennsylvania",
          country: "U.S.A.",
          architects: [
            "Hugh Irvine Wilson",
          ],
          yards: 6886,
          par: 70,
          lat: 40.0018685,
          lng: -75.3118038,
          description: "What a treat it was to see Merion East, long considered the best course on the tightest acreage in America, hosting the 2013 U.S. Open. Today's generation of big hitters couldn't conquer the little old course. They couldn't stay on its canted fairways edged by creeks, hodge-podge rough and OB stakes and they couldn't consistently hit its canted greens edged by bunkers that stare back. Let's hope it doesn't take another 32 years for the U.S. Open to return to Merion.",
        },
        {
          ranking: 11,
          name: "Oakmont",
          image: "../courseAerials/11_Oakmont.jpg",
          yearFounded: 1903,
          privatOrPublic: "Private",
          city: "Oakmont",
          stateOrProvince: "Pennsylvania",
          country: "U.S.A.",
          architects: [
            "Henry Fownes",
          ],
          yards: 7255,
          par: 71,
          lat: 40.5203836,
          lng: -79.8431237,
          description: "With thousands of trees (planted mostly in the 1960s) now removed, Oakmont's penal design is re-established, with the game's most nasty, notorious bunkers (founder-architect H.C. Fownes staked out bunkers whenever and where ever he saw a player hit an offline shot), deep drainage ditches and ankle-deep rough. Oakmont also has the game's swiftest putting surfaces, which will likely be slowed down for the 2016 U.S. Open.",
        },
        {
          ranking: 12,
          name: "Pebble Beach Golf Links",
          image: "../courseAerials/12_PebbleBeach.jpg",
          yearFounded: 1919,
          privatOrPublic: "Public",
          city: "Pebble Beach",
          stateOrProvince: "California",
          country: "U.S.A",
          architects: [
            "Jack Neville",
            "Douglas Grant",
          ],
          yards: 6828,
          par: 72,
          lat: 36.5688064,
          lng: -121.9506241,
          description: "Not just the greatest meeting of land and sea in American golf, but the most extensive one, too, with nine holes perched immediately above the crashing Pacific surf – the fourth through 10th plus the 17th and 18th. Pebble's sixth through eighth are golf's real Amen Corner, with a few Hail Marys thrown in over a ocean cove on eight from atop a 75-foot-high bluff. Pebble will host another U.S. Amateur in 2018, and its sixth U.S. Open in 2019.",
        },
        {
          ranking: 13,
          name: "National Golf Links of America",
          image: "../courseAerials/13_NationalGolfLinks.jpg",
          yearFounded: 	1911,
          privatOrPublic: "Private",
          city: "Southampton",
          stateOrProvince: "New York",
          country: "U.S.A",
          architects: [
            "Charles B. Mac Donald",
          ],
          yards: 6935,
          par: 72,
          lat: 40.9135774,
          lng: -72.4537075,
          description: "As the 2013 Walker Cup reminded us, National Golf Links is a true links containing a marvelous collection of strategic holes. Credit architect C.B. Macdonald, who designed National as a collection of his favorite features from grand old British golf holes. Macdonald's versions are actually superior in strategy to the originals, which is why National's design is still studied by golf architects today.",
        },
        {
          ranking: 14,
          name: "Winged Foot G.C. (West)",
          image: "../courseAerials/14_WingedFoot.jpg",
          yearFounded: 1921,
          privatOrPublic: "Private",
          city: "Mamaroneck",
          stateOrProvince: "New York",
          country: "U.S.A",
          architects: [
            "A. W. Tillinghast",
          ],
          yards: 7258,
          par: 72,
          lat: 40.9576711,
          lng: -73.7534846,
          description: "Gone are all the Norway Spruce that once squeezed every fairway of Winged Foot West. It's now gloriously open and playable, at least until one reaches the putting surfaces, perhaps the finest set of green contours the versatile architect A.W. Tillinghast ever did, now being restored to original parameters by architect Gil Hanse. The greens look like giant mushrooms, curled and slumped around the edges, proving that as a course architect, Tillinghast was not a fun guy. Winged Foot West will host the U.S. Open again in 2020.",
        },
        {
          ranking: 15,
          name: "Fishers Island Club",
          image: "../courseAerials/15_FishersIsland.jpg",
          yearFounded: 1926,
          privatOrPublic: "Private",
          city: "Fishers Island",
          stateOrProvince: "New York",
          country: "U.S.A.",
          architects: [
            "Seth Raynor",
          ],
          yards: 6566,
          par: 72,
          lat: 41.2799343,
          lng: -71.9487709,
          description: "Probably the consummate design of architect Seth Raynor, who died in early 1926, before the course had opened. His steeply-banked bunkers and geometric greens harmonize perfectly with the linear panoramas of the Atlantic Ocean and Long Island Sound. The quality of the holes is also superb, with all of Raynor's usual suspects, including not one but two Redan greens, one on a par 4.",
        },
        {
          ranking: 16,
          name: "Cape Kidnappers",
          image: "../courseAerials/16_CapeKidnappers.jpg",
          yearFounded: 2004,
          privatOrPublic: "Public",
          city: "Te Awanga",
          stateOrProvince: "Hawke's Bay",
          country: "New Zealand",
          architects: [
            "Tom Doak",
          ],
          yards: 7147,
          par: 71,
          lat: -39.6510403,
          lng: 177.0674215,
          description: "Not a links, more like stratospheric Pebble Beach, high atop a windswept plateau some 500 feet above the sea. Its 2004 design truly demonstrates the lay-of-the-land philosophy of architect Tom Doak, who ran holes out and back along a series of ridges perpendicular with the coastline, most framed by deep canyons. The fairways are wide, but Doak rewards bold tee shots that flirt with ravines and some of the deepest bunkers Doak has ever built. Cape Kidnappers was also the International winner of a 2012 Environmental Leaders in Golf Award, co-sponsored by Golf Digest.",
        },
        {
          ranking: 17,
          name: "Sand Hills G.C.",
          image: "../courseAerials/17_SandHills.jpg",
          yearFounded: 1999,
          privatOrPublic: "Private",
          city: "Mullen",
          stateOrProvince: "Nebraska",
          country: "U.S.A.",
          architects: [
            "Bill Coore",
            "Ben Crenshaw",
          ],
          yards: 7089,
          par: 71,
          lat: 41.8673301,
          lng: -101.0946552,
          description: "The golf course wasn't so much designed as discovered. Bill Coore and Ben Crenshaw trudged back and forth over a thousand acres of rolling sand hills in central Nebraska, flagging out naturally-occurring fairways and greens. By moving just 4,000 cubic yards of earth, and letting the winds shape (and reshape) the bunkers, the duo created what is undoubtedly the most natural golf course in America.",
        },
        {
          ranking: 18,
          name: "Kingston Heath G.C.",
          image: "../courseAerials/18_KingstonHeath.jpg",
          yearFounded: 1925,
          privatOrPublic: "Private",
          city: "Cheltenham",
          stateOrProvince: "Victoria",
          country: "Australia",
          architects: [
            "Des Soutar",
            "Alister MacKenzie",
          ],
          yards: 7102,
          par: 72,
          lat: -37.9557812,
          lng: 145.085814,
          description: "Considered an Alister MacKenzie design, but in fact Australian pro Des Soutar designed the course in 1925. MacKenzie made a brief visit the following year and suggested the present bunkering, which was constructed by Mick Morcom before he built Royal Melbourne's two courses. The bunkers are long, sinewy, shaggy, gnarly, windswept and, of course, strategically placed. Some say MacKenzie's tee-to-green stretch of bunkers on the par-3 15th set the standard for all Sandbelt layouts.",
        },
        {
          ranking: 19,
          name: "Cabot Cliffs",
          image: "../courseAerials/19_CabotCliffs.jpg",
          yearFounded: 2016,
          privatOrPublic: "Public",
          city: "Iverness",
          stateOrProvince: "Nova Scotia",
          country: "Canada",
          architects: [
            "Bill Coore",
            "Ben Crenshaw",
          ],
          yards: 6875,
          par: 72,
          lat: 46.2365266,
          lng: -61.3022359,
          description: "The sensational Bill Coore & Ben Crenshaw design overflows with variety with its southernmost holes in Lahinch-like sand dunes, its northernmost atop Pebble Beach-type ocean cliffs. It has six par 5s, including three in the space of four holes, and six par 3s, plus an additional one-shot bye-hole aside the fourth. Sporting the same fescue turf mix as nearby sister course Cabot Links (ranked No. 93), some tee shots seem to roll forever, but so do errant shots that miss greens.",
        },
        {
          ranking: 20,
          name: "Morfontaine",
          image: "../courseAerials/20_Morfontaine.jpg",
          yearFounded: 1927,
          privatOrPublic: "Private",
          city: "Senlis",
          stateOrProvince: "Oise",
          country: "France",
          architects: [
            "Tom Simpson",
            "Kyle Phillips",
          ],
          yards: 6545,
          par: 70,
          lat: 49.1472103,
          lng: 2.6006115,
          description: "A timeless 1927 design north of Paris by British architect Tom Simpson, Morfontaine looks suspiciously like a heathland course around London, with windswept Scotch pines and clumps of heather atop a base of sand. But it's tighter than Sunningdale or St. George's Hill, and the forest surrounding holes is far denser. A decade ago, American architect Kyle Phillips updated the layout, adding a new 12th green to extend the par-5 by 60 yards. It fits in perfectly.",
        },
        {
          ranking: 21,
          name: "Hirono G.C.",
          image: "../courseAerials/21_Hirono.jpg",
          yearFounded: 	1932,
          privatOrPublic: "Public",
          city: "Hirono",
          stateOrProvince: "Hyogo",
          country: "Japan",
          architects: [
            "C.H. Allison",
          ],
          yards: 6925,
          par: 72,
          lat: 34.770391,
          lng: 135.021666,
          description: "Undoubtedly the finest design of globetrotting C.H. Alison, longtime partner of H.S. Colt. He laid out Hirono in the early 1930s in a hilly pine forest slashed by gulleys, clearing wide corridors and positioning greens on the crests of ridges. What makes Hirono special was Alison's spectacular bunkering, which ranged from diagonal cross bunkers, fearsome carry bunkers and strings of ragged-edged ones. Soon after completion, writers were calling Hirono the Pine Valley of Japan.",
        },
        {
          ranking: 22,
          name: "Trump Turnberry Resort",
          image: "../courseAerials/22_Turnberry.jpg",
          yearFounded: 1906,
          privatOrPublic: "Private",
          city: "Turnberry",
          stateOrProvince: "Ayrshire",
          country: "Scotland",
          architects: [
            "Willie Fernie",
            "Mackenzie Ross",
          ],
          yards: 7452,
          par: 70,
          lat: 55.3140916,
          lng: -4.8286586,
          description: "A legendary links ravaged by WWII, it was re-established to its present quality by architect Philip Mackenzie Ross, who tore away concrete landing strips to create a dramatic back nine and built a set of varied greens, some receptive, other not so much. After its recent purchase by Donald Trump, Martin Ebert is busy making notable changes, creating a new par-3 sixth, converting the old par-4 9th into a new par 3, turning the 10th and 14th into par 5s and the 17th into a long par 4. New tees on 18 eliminate its dogleg tee shot. Plus, Ebert is replacing revetted bunkers with ragged-edge ones. The revamped course reopens in June 2016.",
        },
        {
          ranking: 23,
          name: "Sunningdale G.C.",
          image: "../courseAerials/23_Sunningdale.jpg",
          yearFounded: 1900,
          privatOrPublic: "Private",
          city: "Ascot",
          stateOrProvince: "Berkshire",
          country: "England",
          architects: [
            "Willie Park Jr.",
          ],
          yards: 6627,
          par: 70,
          lat: 51.3887942,
          lng: -0.6313613,
          description: "A Willie Park Jr. design that dates from 1901, it's perhaps the most advanced design of its day. Chopped from a pine forest but designed like a links, with the ninth at far end of property, it plays like a links, too, for there's a sand base beneath the turf. The Old has big greens, as Park put a premium on approach putting, and artful bunkers, with both angled cross bunkers and necklaces of sand hampering direct routes to some greens. To American visitors, the look of Sunningdale brings to mind Pine Valley or Pinehurst.",
        },
        {
          ranking: 24,
          name: "Cape Wickham Links",
          image: "../courseAerials/24_CapeWickham.jpg",
          yearFounded: 2015,
          privatOrPublic: "Public",
          city: "King Island",
          stateOrProvince: "Tasmania",
          country: "Australia",
          architects: [
            "Mike DeVries",
            "Darius Oliver",
          ],
          yards: 6725,
          par: 72,
          lat: -39.5956617,
          lng: 143.9325933,
          description: "This design collaboration by American Mike DeVries and Australian golf writer Darius Oliver may be an even bigger surprise than No. 19 Cabot Cliffs. It's a glorious collection of holes on a breathtaking site along Bass Strait, a notorious stretch of Australian seacoast that once shipwrecked many voyages. Its routing is heart-pounding, starting along rocks and crashing surf, moving inland but not out of the wind, returning to ocean edge at the downhill 10th, pitch-shot 11th and drivable par-4 12th, then wandering into dunes before a crescendo closing hole curving along Victoria Cove beach, which is in play at low tides.",
        },
        {
          ranking: 25,
          name: "Portmarnock G.C.",
          image: "../courseAerials/25_Portmarnock.jpg",
          yearFounded: 1894,
          privatOrPublic: "Private",
          city: "Portmarnock",
          stateOrProvince: "Dublin",
          country: "Ireland",
          architects: [
            "William Pickeman",
          ],
          yards: 7365,
          par: 72,
          lat: 53.407192,
          lng: -6.1238479,
          description: "A true links in rolling ground with soft rather than dramatic dunes, Portmarnock, on a spit of land on the Irish Sea north of Dublin, is known for its routing, which hasn't been altered in over a hundred years and was revolutionary at the time for constantly changing wind direction with every shot. The links is also known for its fairness, as nearly every feature is plainly in view from tee to green. Which makes its maze of bunkers and subtle greens all the more testing.",
        },
        {
          ranking: 26,
          name: "Carnoustie Golf Links",
          image: "../courseAerials/26_Carnoustie.jpg",
          yearFounded: 1850,
          privatOrPublic: "Public",
          city: "Carnoustie",
          stateOrProvince: "Angus",
          country: "Scotland",
          architects: [
            "Old Tom Morris",
            "James Braid",
            "Allan Robertson",
          ],
          yards: 7421,
          par: 71,
          lat: 56.4971417,
          lng: -2.7165037,
          description: "Perhaps the homeliest, certainly the longest and toughest of Open venues, Carnoustie is a no-holds-barred layout intended to test the best. James Braid is usually credited with the present design, but it was green chairman James Wright who in 1931 created the stirring last three holes, with 17 and 18 harassed by twisting, turning Barry Burn. In the 1968 Open, Jack Nicklaus complained that a knob in the middle of the ninth fairway kicked his drives into the rough. When he returned for the 1975 Open, he found it had been converted to a pot bunker.",
        },
        {
          ranking: 27,
          name: "Royal Portrush G.C.",
          image: "../courseAerials/27_RoyalPortrush.jpg",
          yearFounded: 1888,
          privatOrPublic: "Private",
          city: "Portrush",
          stateOrProvince: "Antrim",
          country: "Northern Ireland",
          architects: [
            "Old Tom Morris",
            "H.S. Colt",
            "Martin Ebert",
          ],
          yards: 7337,
          par: 72,
          lat: 55.199619,
          lng: -6.635946,
          description: "Portrush is still the only Irish course to host The Open. The Old Tom Morris design, reworked by H.S. Colt in the 1930s, was the Open site back in 1951, and will be again in 2019. In preparation, architect Martin Ebert is adding new sixth and seventh holes, fashioned from land on the club's Valley Course, to replace the weak 17th and 18th. That means the notorious Calamity Hole, an uphill 210-yard par 3, will now be the 16th instead of the 14th, and the old dogleg-right, par-4 16th will now be the closing hole, with a new back tee. Ebert is retaining Colt's greens, considered one of the best set of putting surfaces in the world.",
        },
        {
          ranking: 28,
          name: "Seminole G.C.",
          image: "../courseAerials/28_Seminole.jpg",
          yearFounded: 1929,
          privatOrPublic: "Private",
          city: "Juno Beach",
          stateOrProvince: "Florida",
          country: "U.S.A.",
          architects: [
            "Donald Ross",
            "Dick Wilson",
          ],
          yards: 6836,
          par: 72,
          lat: 26.8600684,
          lng: -80.0473388,
          description: "A majestic Donald Ross design with a clever routing on a rectangular site, each hole at Seminole encounters a new wind direction. The greens are no longer Ross, replaced 50 years ago in a regrassing effort that showed little appreciation for the original rolling contours. The bunkers aren't Ross either. Dick Wilson replaced them in 1947, his own version meant to the imitate crests of waves on the adjacent Atlantic. Seminole has long been one of America's most exclusive clubs, which is why it's exciting that it will host the 2021 Walker Cup.",
        },
        {
          ranking: 29,
          name: "Ellerston G.C.",
          image: "../courseAerials/29_Ellerston.jpg",
          yearFounded: 2001,
          privatOrPublic: "Private",
          city: "Hunter Valley",
          stateOrProvince: "New South Wales",
          country: "Australia",
          architects: [
            "Greg Norman",
            "Bob Harrison",
          ],
          yards: 7318,
          par: 72,
          lat: -31.7975927,
          lng: 151.3037323,
          description: "No other course on the World Top 100 is so brutally honest about its intention to be a ball buster. The late media mogul Kerry Packer commissioned Greg Norman to build him the nation's toughest course, and Norman complied. Routed on slopes and in a valley on Packer's estate, it has water in play on half the holes. A superb aerial game is needed to clear deep bunkers and reach greens perched perilously close to the Pages Creek. After Ellerston's opening, Norman said, 'We had no need to consider forward tees, resort traffic or weaker hitters. We were able to create a course that a golfer of my caliber would love to play everyday.'",
        },
        {
          ranking: 30,
          name: "New South Wales G.C.",
          image: "../courseAerials/30_NewSouthWales.jpg",
          yearFounded: 1926,
          privatOrPublic: "Private",
          city: "Le Perouse, ,  / 6,829 yards, Par 72",
          stateOrProvince: "New South Wales",
          country: "Australia",
          architects: [
            "Alister MacKenzie",
            "Eric Apperly",
            "Greg Norman",
          ],
          yards: 6829,
          par: 72,
          lat: -33.9911926,
          lng: 151.2403335,
          description: "Sitting along the dramatic rugged seacoast of Botany Bay near Sydney, on the spot where Captain Cook first stepped onto Australia in 1770, La Perouse is renown for its ocean views and high winds. On his brief but productive 1926 trip, Alister MacKenzie prepared a routing for the course, but it was radically altered during a 1936 remodeling by Eric Apperly and by neglect during WWII. A succession of post-war architects have slowly re-established the integrity of the design, most recently Greg Norman.",
        },
        // {
        //   ranking: 31,
        //   name: "",
        //   image: "../courseAerials/_.jpg",
        //   yearFounded: ,
        //   privatOrPublic: "",
        //   city: "",
        //   stateOrProvince: "",
        //   country: "",
        //   architects: [
        //     "",
        //     "",
        //   ],
        //   yards: ,
        //   par: ,
        //   lat: ,
        //   lng: ,
        //   description: "",
        // },
        // {
        //   ranking: 32,
        //   name: "",
        //   image: "../courseAerials/_.jpg",
        //   yearFounded: ,
        //   privatOrPublic: "",
        //   city: "",
        //   stateOrProvince: "",
        //   country: "",
        //   architects: [
        //     "",
        //     "",
        //   ],
        //   yards: ,
        //   par: ,
        //   lat: ,
        //   lng: ,
        //   description: "",
        // },
        // {
        //   ranking: 33,
        //   name: "",
        //   image: "../courseAerials/_.jpg",
        //   yearFounded: ,
        //   privatOrPublic: "",
        //   city: "",
        //   stateOrProvince: "",
        //   country: "",
        //   architects: [
        //     "",
        //     "",
        //   ],
        //   yards: ,
        //   par: ,
        //   lat: ,
        //   lng: ,
        //   description: "",
        // },
        // {
        //   ranking: 34,
        //   name: "",
        //   image: "../courseAerials/_.jpg",
        //   yearFounded: ,
        //   privatOrPublic: "",
        //   city: "",
        //   stateOrProvince: "",
        //   country: "",
        //   architects: [
        //     "",
        //     "",
        //   ],
        //   yards: ,
        //   par: ,
        //   lat: ,
        //   lng: ,
        //   description: "",
        // },
        // {
        //   ranking: 35,
        //   name: "",
        //   image: "../courseAerials/_.jpg",
        //   yearFounded: ,
        //   privatOrPublic: "",
        //   city: "",
        //   stateOrProvince: "",
        //   country: "",
        //   architects: [
        //     "",
        //     "",
        //   ],
        //   yards: ,
        //   par: ,
        //   lat: ,
        //   lng: ,
        //   description: "",
        // },
        // {
        //   ranking: 36,
        //   name: "",
        //   image: "../courseAerials/_.jpg",
        //   yearFounded: ,
        //   privatOrPublic: "",
        //   city: "",
        //   stateOrProvince: "",
        //   country: "",
        //   architects: [
        //     "",
        //     "",
        //   ],
        //   yards: ,
        //   par: ,
        //   lat: ,
        //   lng: ,
        //   description: "",
        // },
        // {
        //   ranking: 37,
        //   name: "",
        //   image: "../courseAerials/_.jpg",
        //   yearFounded: ,
        //   privatOrPublic: "",
        //   city: "",
        //   stateOrProvince: "",
        //   country: "",
        //   architects: [
        //     "",
        //     "",
        //   ],
        //   yards: ,
        //   par: ,
        //   lat: ,
        //   lng: ,
        //   description: "",
        // },
        // {
        //   ranking: 38,
        //   name: "",
        //   image: "../courseAerials/_.jpg",
        //   yearFounded: ,
        //   privatOrPublic: "",
        //   city: "",
        //   stateOrProvince: "",
        //   country: "",
        //   architects: [
        //     "",
        //     "",
        //   ],
        //   yards: ,
        //   par: ,
        //   lat: ,
        //   lng: ,
        //   description: "",
        // },
        // {
        //   ranking: 39,
        //   name: "",
        //   image: "../courseAerials/_.jpg",
        //   yearFounded: ,
        //   privatOrPublic: "",
        //   city: "",
        //   stateOrProvince: "",
        //   country: "",
        //   architects: [
        //     "",
        //     "",
        //   ],
        //   yards: ,
        //   par: ,
        //   lat: ,
        //   lng: ,
        //   description: "",
        // },
        // {
        //   ranking: 40,
        //   name: "",
        //   image: "../courseAerials/_.jpg",
        //   yearFounded: ,
        //   privatOrPublic: "",
        //   city: "",
        //   stateOrProvince: "",
        //   country: "",
        //   architects: [
        //     "",
        //     "",
        //   ],
        //   yards: ,
        //   par: ,
        //   lat: ,
        //   lng: ,
        //   description: "",
        // },
        // {
        //   ranking: 41,
        //   name: "",
        //   image: "../courseAerials/_.jpg",
        //   yearFounded: ,
        //   privatOrPublic: "",
        //   city: "",
        //   stateOrProvince: "",
        //   country: "",
        //   architects: [
        //     "",
        //     "",
        //   ],
        //   yards: ,
        //   par: ,
        //   lat: ,
        //   lng: ,
        //   description: "",
        // },
        // {
        //   ranking: 42,
        //   name: "",
        //   image: "../courseAerials/_.jpg",
        //   yearFounded: ,
        //   privatOrPublic: "",
        //   city: "",
        //   stateOrProvince: "",
        //   country: "",
        //   architects: [
        //     "",
        //     "",
        //   ],
        //   yards: ,
        //   par: ,
        //   lat: ,
        //   lng: ,
        //   description: "",
        // },
        // {
        //   ranking: 43,
        //   name: "",
        //   image: "../courseAerials/_.jpg",
        //   yearFounded: ,
        //   privatOrPublic: "",
        //   city: "",
        //   stateOrProvince: "",
        //   country: "",
        //   architects: [
        //     "",
        //     "",
        //   ],
        //   yards: ,
        //   par: ,
        //   lat: ,
        //   lng: ,
        //   description: "",
        // },
        // {
        //   ranking: 44,
        //   name: "",
        //   image: "../courseAerials/_.jpg",
        //   yearFounded: ,
        //   privatOrPublic: "",
        //   city: "",
        //   stateOrProvince: "",
        //   country: "",
        //   architects: [
        //     "",
        //     "",
        //   ],
        //   yards: ,
        //   par: ,
        //   lat: ,
        //   lng: ,
        //   description: "",
        // },
        // {
        //   ranking: 45,
        //   name: "",
        //   image: "../courseAerials/_.jpg",
        //   yearFounded: ,
        //   privatOrPublic: "",
        //   city: "",
        //   stateOrProvince: "",
        //   country: "",
        //   architects: [
        //     "",
        //     "",
        //   ],
        //   yards: ,
        //   par: ,
        //   lat: ,
        //   lng: ,
        //   description: "",
        // },
        // {
        //   ranking: 46,
        //   name: "",
        //   image: "../courseAerials/_.jpg",
        //   yearFounded: ,
        //   privatOrPublic: "",
        //   city: "",
        //   stateOrProvince: "",
        //   country: "",
        //   architects: [
        //     "",
        //     "",
        //   ],
        //   yards: ,
        //   par: ,
        //   lat: ,
        //   lng: ,
        //   description: "",
        // },
        // {
        //   ranking: 47,
        //   name: "",
        //   image: "../courseAerials/_.jpg",
        //   yearFounded: ,
        //   privatOrPublic: "",
        //   city: "",
        //   stateOrProvince: "",
        //   country: "",
        //   architects: [
        //     "",
        //     "",
        //   ],
        //   yards: ,
        //   par: ,
        //   lat: ,
        //   lng: ,
        //   description: "",
        // },
        // {
        //   ranking: 48,
        //   name: "",
        //   image: "../courseAerials/_.jpg",
        //   yearFounded: ,
        //   privatOrPublic: "",
        //   city: "",
        //   stateOrProvince: "",
        //   country: "",
        //   architects: [
        //     "",
        //     "",
        //   ],
        //   yards: ,
        //   par: ,
        //   lat: ,
        //   lng: ,
        //   description: "",
        // },
        // {
        //   ranking: 49,
        //   name: "",
        //   image: "../courseAerials/_.jpg",
        //   yearFounded: ,
        //   privatOrPublic: "",
        //   city: "",
        //   stateOrProvince: "",
        //   country: "",
        //   architects: [
        //     "",
        //     "",
        //   ],
        //   yards: ,
        //   par: ,
        //   lat: ,
        //   lng: ,
        //   description: "",
        // },
        // {
        //   ranking: 50,
        //   name: "",
        //   image: "../courseAerials/_.jpg",
        //   yearFounded: ,
        //   privatOrPublic: "",
        //   city: "",
        //   stateOrProvince: "",
        //   country: "",
        //   architects: [
        //     "",
        //     "",
        //   ],
        //   yards: ,
        //   par: ,
        //   lat: ,
        //   lng: ,
        //   description: "",
        // },
      ]);
    });
};
