
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('courses').del()
    .then(function () {
      // Inserts seed entries
      return knex('courses').insert([
        {
          ranking: 1,
          name: "Royal County Down G.C.",
          image: "",
          yearFounded: 1889,
          city: "Newcastle",
          stateOrProvince: "County Down",
          country: "Northern Ireland",
          architect: "Old Tom Morris",
          yards: 7186,
          par: 71,
          lat: 54.216937,
          lng: -5.885974,
          description: "On a clear spring day, with Dundrum Bay to the east, the Mountains of Mourne to the south and gorse-covered dunes in golden bloom, there is no lovelier place in golf than our new No. 1. Its design is attributed to Old Tom Morris but was refined by half a dozen architects in the past 120 years, most recently by Donald Steel. Though the greens are surprisingly flat, as if to compensate for the rugged terrain and numerous blind shots, bunkers are a definite highlight, most with arched eyebrows of dense marram grasses and impenetrable clumps of heather.",
        },
        {
          ranking: 2,
          name: "Augusta National G.C.",
          image: "",
          yearFounded: 1933,
          city: "Augusta, Ga., U.S.A. / 7,435 yards, Par 72",
          stateOrProvince: "Georgia",
          country: "U.S.A.",
          architect: "Bobby Jones",
          yards: 7435,
          par: 72,
          lat: 33.5021365,
          lng: -82.0226276,
          description: "No club has tinkered with its golf course as often or as effectively over the decades as has Augusta National, mainly to keep it competitive for the annual Masters Tournament, an event it has conducted since 1934, with time off during WWII. All that tinkering has resulted in an amalgamation of design ideas, with a routing by Alister MacKenzie and Bob Jones, some Perry Maxwell greens, some Trent Jones water hazards, some Jack Nicklaus mounds and, in the last decade, extensive lengthening and rebunkering by Tom Fazio.",
        },
        {
          ranking: 3,
          name: "Pine Valley G.C.",
          image: "",
          yearFounded: 1913,
          city: "Pine Valley, N.J., U.S.A. / 7,057 yards, Par 70",
          stateOrProvince: "New Jersey",
          country: "U.S.A.",
          architect: "George Crump",
          yards: 7057,
          par: 70,
          lat: 39.7921578,
          lng: -74.9714701,
          description: "A genuine original, its unique character was forged from the sandy pine barrens of southwest Jersey. Founder George Crump had help from architects H.S. Colt, A.W. Tillinghast, George C. Thomas Jr. and Walter Travis. Hugh Wilson of Merion fame finished the job. Pine Valley blends all three schools of golf design – penal, heroic and strategic – throughout the course, often times on a single hole.",
        },
        {
          ranking: 4,
          name: "Cypress Point Club",
          image: "",
          yearFounded: 1928,
          city: "Pebble Beach",
          stateOrProvince: "California",
          country: "U.S.A.",
          architect: "Alister MacKenzie",
          yards: 6524,
          par: 72,
          lat: ,
          lng: ,
          description: "Alister MacKenzie's masterpiece, woven through cypress, sand dunes and jagged coastline. In the 2000s, member Sandy Tatum, a former USGA president who christened Cypress Point as the Sistine Chapel of golf, convinced the club not to combat technology by adding new back tees, but instead make a statement by celebrating its original architecture. So Cypress remains timeless, if short, its charm helped in part by re-establishment of MacKenzie's fancy bunkering.",
        },
        {
          ranking: 5,
          name: "",
          image: "",
          yearFounded: ,
          city: "",
          stateOrProvince: "",
          country: "",
          architect: "",
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 6,
          name: "",
          image: "",
          yearFounded: ,
          city: "",
          stateOrProvince: "",
          country: "",
          architect: "",
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 7,
          name: "",
          image: "",
          yearFounded: ,
          city: "",
          stateOrProvince: "",
          country: "",
          architect: "",
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 8,
          name: "",
          image: "",
          yearFounded: ,
          city: "",
          stateOrProvince: "",
          country: "",
          architect: "",
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 9,
          name: "",
          image: "",
          yearFounded: ,
          city: "",
          stateOrProvince: "",
          country: "",
          architect: "",
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 10,
          name: "",
          image: "",
          yearFounded: ,
          city: "",
          stateOrProvince: "",
          country: "",
          architect: "",
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 11,
          name: "",
          image: "",
          yearFounded: ,
          city: "",
          stateOrProvince: "",
          country: "",
          architect: "",
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 12,
          name: "",
          image: "",
          yearFounded: ,
          city: "",
          stateOrProvince: "",
          country: "",
          architect: "",
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 13,
          name: "",
          image: "",
          yearFounded: ,
          city: "",
          stateOrProvince: "",
          country: "",
          architect: "",
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 14,
          name: "",
          image: "",
          yearFounded: ,
          city: "",
          stateOrProvince: "",
          country: "",
          architect: "",
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 15,
          name: "",
          image: "",
          yearFounded: ,
          city: "",
          stateOrProvince: "",
          country: "",
          architect: "",
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 16,
          name: "",
          image: "",
          yearFounded: ,
          city: "",
          stateOrProvince: "",
          country: "",
          architect: "",
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 17,
          name: "",
          image: "",
          yearFounded: ,
          city: "",
          stateOrProvince: "",
          country: "",
          architect: "",
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 18,
          name: "",
          image: "",
          yearFounded: ,
          city: "",
          stateOrProvince: "",
          country: "",
          architect: "",
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 19,
          name: "",
          image: "",
          yearFounded: ,
          city: "",
          stateOrProvince: "",
          country: "",
          architect: "",
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 20,
          name: "",
          image: "",
          yearFounded: ,
          city: "",
          stateOrProvince: "",
          country: "",
          architect: "",
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 21,
          name: "",
          image: "",
          yearFounded: ,
          city: "",
          stateOrProvince: "",
          country: "",
          architect: "",
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 22,
          name: "",
          image: "",
          yearFounded: ,
          city: "",
          stateOrProvince: "",
          country: "",
          architect: "",
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 23,
          name: "",
          image: "",
          yearFounded: ,
          city: "",
          stateOrProvince: "",
          country: "",
          architect: "",
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 24,
          name: "",
          image: "",
          yearFounded: ,
          city: "",
          stateOrProvince: "",
          country: "",
          architect: "",
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 25,
          name: "",
          image: "",
          yearFounded: ,
          city: "",
          stateOrProvince: "",
          country: "",
          architect: "",
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 26,
          name: "",
          image: "",
          yearFounded: ,
          city: "",
          stateOrProvince: "",
          country: "",
          architect: "",
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 27,
          name: "",
          image: "",
          yearFounded: ,
          city: "",
          stateOrProvince: "",
          country: "",
          architect: "",
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 28,
          name: "",
          image: "",
          yearFounded: ,
          city: "",
          stateOrProvince: "",
          country: "",
          architect: "",
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 29,
          name: "",
          image: "",
          yearFounded: ,
          city: "",
          stateOrProvince: "",
          country: "",
          architect: "",
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 30,
          name: "",
          image: "",
          yearFounded: ,
          city: "",
          stateOrProvince: "",
          country: "",
          architect: "",
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 31,
          name: "",
          image: "",
          yearFounded: ,
          city: "",
          stateOrProvince: "",
          country: "",
          architect: "",
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 32,
          name: "",
          image: "",
          yearFounded: ,
          city: "",
          stateOrProvince: "",
          country: "",
          architect: "",
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 33,
          name: "",
          image: "",
          yearFounded: ,
          city: "",
          stateOrProvince: "",
          country: "",
          architect: "",
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 34,
          name: "",
          image: "",
          yearFounded: ,
          city: "",
          stateOrProvince: "",
          country: "",
          architect: "",
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 35,
          name: "",
          image: "",
          yearFounded: ,
          city: "",
          stateOrProvince: "",
          country: "",
          architect: "",
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 36,
          name: "",
          image: "",
          yearFounded: ,
          city: "",
          stateOrProvince: "",
          country: "",
          architect: "",
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 37,
          name: "",
          image: "",
          yearFounded: ,
          city: "",
          stateOrProvince: "",
          country: "",
          architect: "",
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 38,
          name: "",
          image: "",
          yearFounded: ,
          city: "",
          stateOrProvince: "",
          country: "",
          architect: "",
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 39,
          name: "",
          image: "",
          yearFounded: ,
          city: "",
          stateOrProvince: "",
          country: "",
          architect: "",
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 40,
          name: "",
          image: "",
          yearFounded: ,
          city: "",
          stateOrProvince: "",
          country: "",
          architect: "",
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 41,
          name: "",
          image: "",
          yearFounded: ,
          city: "",
          stateOrProvince: "",
          country: "",
          architect: "",
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 42,
          name: "",
          image: "",
          yearFounded: ,
          city: "",
          stateOrProvince: "",
          country: "",
          architect: "",
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 43,
          name: "",
          image: "",
          yearFounded: ,
          city: "",
          stateOrProvince: "",
          country: "",
          architect: "",
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 44,
          name: "",
          image: "",
          yearFounded: ,
          city: "",
          stateOrProvince: "",
          country: "",
          architect: "",
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 45,
          name: "",
          image: "",
          yearFounded: ,
          city: "",
          stateOrProvince: "",
          country: "",
          architect: "",
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 46,
          name: "",
          image: "",
          yearFounded: ,
          city: "",
          stateOrProvince: "",
          country: "",
          architect: "",
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 47,
          name: "",
          image: "",
          yearFounded: ,
          city: "",
          stateOrProvince: "",
          country: "",
          architect: "",
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 48,
          name: "",
          image: "",
          yearFounded: ,
          city: "",
          stateOrProvince: "",
          country: "",
          architect: "",
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 49,
          name: "",
          image: "",
          yearFounded: ,
          city: "",
          stateOrProvince: "",
          country: "",
          architect: "",
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 50,
          name: "",
          image: "",
          yearFounded: ,
          city: "",
          stateOrProvince: "",
          country: "",
          architect: "",
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
      ]);
    });
};
