
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('courses').del()
    .then(function () {
      // Inserts seed entries
      return knex('courses').insert([
        {
          ranking: 1,
          name: "Royal County Down G.C.",
          image: "",
          yearFounded: 1889,
          privatOrPublic: "Private/Public",
          city: "Newcastle",
          stateOrProvince: "County Down",
          country: "Northern Ireland",
          architects: [
            "Old Tom Morris",
          ],
          yards: 7186,
          par: 71,
          lat: 54.216937,
          lng: -5.885974,
          description: "On a clear spring day, with Dundrum Bay to the east, the Mountains of Mourne to the south and gorse-covered dunes in golden bloom, there is no lovelier place in golf than our new No. 1. Its design is attributed to Old Tom Morris but was refined by half a dozen architects in the past 120 years, most recently by Donald Steel. Though the greens are surprisingly flat, as if to compensate for the rugged terrain and numerous blind shots, bunkers are a definite highlight, most with arched eyebrows of dense marram grasses and impenetrable clumps of heather.",
        },
        {
          ranking: 2,
          name: "Augusta National G.C.",
          image: "",
          yearFounded: 1933,
          privatOrPublic: "Private",
          city: "Augusta, Ga., U.S.A. / 7,435 yards, Par 72",
          stateOrProvince: "Georgia",
          country: "U.S.A.",
          architects: [
            "Bobby Jones",
            "Alister MacKenzie",
          ],
          yards: 7435,
          par: 72,
          lat: 33.5021365,
          lng: -82.0226276,
          description: "No club has tinkered with its golf course as often or as effectively over the decades as has Augusta National, mainly to keep it competitive for the annual Masters Tournament, an event it has conducted since 1934, with time off during WWII. All that tinkering has resulted in an amalgamation of design ideas, with a routing by Alister MacKenzie and Bob Jones, some Perry Maxwell greens, some Trent Jones water hazards, some Jack Nicklaus mounds and, in the last decade, extensive lengthening and rebunkering by Tom Fazio.",
        },
        {
          ranking: 3,
          name: "Pine Valley G.C.",
          image: "",
          yearFounded: 1913,
          privatOrPublic: "Private",
          city: "Pine Valley, N.J., U.S.A. / 7,057 yards, Par 70",
          stateOrProvince: "New Jersey",
          country: "U.S.A.",
          architects: [
            "George Crump",
            "Harry Colt",
            "Charles Hugh Alison",
            "A. W. Tillinghast",
            "Perry Maxwell",
          ],
          yards: 7057,
          par: 70,
          lat: 39.7921578,
          lng: -74.9714701,
          description: "A genuine original, its unique character was forged from the sandy pine barrens of southwest Jersey. Founder George Crump had help from architects H.S. Colt, A.W. Tillinghast, George C. Thomas Jr. and Walter Travis. Hugh Wilson of Merion fame finished the job. Pine Valley blends all three schools of golf design – penal, heroic and strategic – throughout the course, often times on a single hole.",
        },
        {
          ranking: 4,
          name: "Cypress Point Club",
          image: "",
          yearFounded: 1928,
          privatOrPublic: "Private",
          city: "Pebble Beach",
          stateOrProvince: "California",
          country: "U.S.A.",
          architects: [
            "Alister MacKenzie",
            "Robert Hunter",
          ],
          yards: 6524,
          par: 72,
          lat: 36.5802249,
          lng: -121.9741049,
          description: "Alister MacKenzie's masterpiece, woven through cypress, sand dunes and jagged coastline. In the 2000s, member Sandy Tatum, a former USGA president who christened Cypress Point as the Sistine Chapel of golf, convinced the club not to combat technology by adding new back tees, but instead make a statement by celebrating its original architecture. So Cypress remains timeless, if short, its charm helped in part by re-establishment of MacKenzie's fancy bunkering.",
        },
        {
          ranking: 5,
          name: "Royal Dornoch G.C.",
          image: "",
          yearFounded: 1877,
          privatOrPublic: "Public",
          city: "Dornoch",
          stateOrProvince: "Sutherland",
          country: "Scotland",
          architects: [
            "Old Tom Morris",
          ],
          yards: 6704,
          par: 70,
          lat: 57.879296,
          lng: -4.023886,
          description: "Herbert Warren Wind called it the most natural course in the world. Tom Watson called it the most fun he'd had playing golf. Donald Ross called it his home, having been born in the village and learned the game on the links. Tucked in an arc of dunes along the North Sea shoreline, Dornoch's greens, some by Old Tom Morris, others by John Sutherland or tour pro George Duncan, sit mostly on plateaus and don't really favor bounce-and-run golf. That's the challenge. Hitting those greens in a Dornoch wind.",
        },
        {
          ranking: 6,
          name: "Royal Melbourne G.C. (West)",
          image: "",
          yearFounded: 1891,
          privatOrPublic: "Private",
          city: "Melbourne",
          stateOrProvince: "Victoria",
          country: "Australia",
          architects: [
            "Sir James McBain",
            "Alister MacKenzie",
          ],
          yards: 6643,
          par: 72,
          lat: -37.9678325,
          lng: 145.0253219,
          description: "Alister MacKenzie's 1926 routing fits snuggly into the contours of the rolling sandbelt land. His greens are miniature versions of the surrounding topography. His crisp bunkering, with vertical edges a foot or more tall, chew into fairways and putting surfaces. Most holes dogleg, so distance means nothing and angle into the pin is everything. For championships, holes 8 & 9 and 13 - 16 are skipped in favor of six from the East Course, which is ranked No. 55. That 'composite course' was once ranked by several publications.",
        },
        {
          ranking: 7,
          name: "Shinnecock Hills G.C.",
          image: "",
          yearFounded: 1891,
          privatOrPublic: "Private",
          city: "Southampton",
          stateOrProvince: "New York",
          country: "U.S.A.",
          architects: [
            "William Flynn",
            "C.B. MacDonald",
            "Willie Dunn",
            "Willie Davis",
          ],
          yards: 7041,
          par: 70,
          lat: 40.896436,
          lng: -72.440609,
          description: "Generally considered to be the earliest links in America, heavily remodeled twice by C.B. Macdonald, then replaced (except for three holes) by William S. Flynn in the early 1930s. It's so sublime that its architecture hasn't really been fiddled with in nearly 50 years, although the team of Bill Coore and Ben Crenshaw have restored interesting features to prepare Shinnecock for the 2018 U.S. Open.",
        },
        {
          ranking: 8,
          name: "The Old Course at St. Andrews Links",
          image: "",
          yearFounded: 1552,
          privatOrPublic: "Private/Public",
          city: "St. Andrews, ,  /  yards, Par 72",
          stateOrProvince: "Fife",
          country: "Scotland",
          architects: [
            "Old Tom Morris",
          ],
          yards: 7279,
          par: 72,
          lat: 56.3428104,
          lng: -2.802694,
          description: "The Old Course at St. Andrews is ground zero for all golf architecture. Every course designed since has either been in response to one or more of its features, or in reaction against it. Architects either favor the Old Course's blind shots or detest them, either embrace St. Andrews's enormous greens or consider them a waste of turf. Latest polarizing topic: Martin Hawtree's design changes in advance of the 2015 British Open. Many considered it blasphemy beforehand. After Zach Johnson's dramatic overtime victory, few mentioned the alterations.",
        },
        {
          ranking: 9,
          name: "Muirfield",
          image: "",
          yearFounded: 1891,
          privatOrPublic: "Private",
          city: "Gullane",
          stateOrProvince: "East Lothian",
          country: "Scotland",
          architects: [
            "Old Tom Morris",
          ],
          yards: 7209,
          par: 71,
          lat: 56.041578,
          lng: -2.8211708,
          description: "Muirfield is universally admired as a low-key, straightforward links with fairways seemingly containing a million traffic bumps. Except for a blind tee shot on the 11th, every shot is visible and well-defined. Greens are the correct size to fit the expected iron of approach. The routing changes direction on every hole to pose different wind conditions. The front runs clockwise, the back counterclockwise, but history mistakenly credits Old Tom Morris with Muirfield's returning nines. That was the result of H.S. Colt's 1925 redesign.",
        },
        {
          ranking: 10,
          name: "Merion G.C. (East)",
          image: "",
          yearFounded: 1912,
          privatOrPublic: "Private",
          city: "Ardmore",
          stateOrProvince: "Pennsylvania",
          country: "U.S.A.",
          architects: [
            "Hugh Irvine Wilson",
          ],
          yards: 6886,
          par: 70,
          lat: 40.0018685,
          lng: -75.3118038,
          description: "What a treat it was to see Merion East, long considered the best course on the tightest acreage in America, hosting the 2013 U.S. Open. Today's generation of big hitters couldn't conquer the little old course. They couldn't stay on its canted fairways edged by creeks, hodge-podge rough and OB stakes and they couldn't consistently hit its canted greens edged by bunkers that stare back. Let's hope it doesn't take another 32 years for the U.S. Open to return to Merion.",
        },
        {
          ranking: 11,
          name: "",
          image: "",
          yearFounded: ,
          privatOrPublic: "",
          city: "",
          stateOrProvince: "",
          country: "",
          architects: [
            "",
            "",
          ],
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 12,
          name: "",
          image: "",
          yearFounded: ,
          privatOrPublic: "",
          city: "",
          stateOrProvince: "",
          country: "",
          architects: [
            "",
            "",
          ],
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 13,
          name: "",
          image: "",
          yearFounded: ,
          privatOrPublic: "",
          city: "",
          stateOrProvince: "",
          country: "",
          architects: [
            "",
            "",
          ],
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 14,
          name: "",
          image: "",
          yearFounded: ,
          privatOrPublic: "",
          city: "",
          stateOrProvince: "",
          country: "",
          architects: [
            "",
            "",
          ],
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 15,
          name: "",
          image: "",
          yearFounded: ,
          privatOrPublic: "",
          city: "",
          stateOrProvince: "",
          country: "",
          architects: [
            "",
            "",
          ],
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 16,
          name: "",
          image: "",
          yearFounded: ,
          privatOrPublic: "",
          city: "",
          stateOrProvince: "",
          country: "",
          architects: [
            "",
            "",
          ],
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 17,
          name: "",
          image: "",
          yearFounded: ,
          privatOrPublic: "",
          city: "",
          stateOrProvince: "",
          country: "",
          architects: [
            "",
            "",
          ],
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 18,
          name: "",
          image: "",
          yearFounded: ,
          privatOrPublic: "",
          city: "",
          stateOrProvince: "",
          country: "",
          architects: [
            "",
            "",
          ],
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 19,
          name: "",
          image: "",
          yearFounded: ,
          privatOrPublic: "",
          city: "",
          stateOrProvince: "",
          country: "",
          architects: [
            "",
            "",
          ],
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 20,
          name: "",
          image: "",
          yearFounded: ,
          privatOrPublic: "",
          city: "",
          stateOrProvince: "",
          country: "",
          architects: [
            "",
            "",
          ],
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 21,
          name: "",
          image: "",
          yearFounded: ,
          privatOrPublic: "",
          city: "",
          stateOrProvince: "",
          country: "",
          architects: [
            "",
            "",
          ],
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 22,
          name: "",
          image: "",
          yearFounded: ,
          privatOrPublic: "",
          city: "",
          stateOrProvince: "",
          country: "",
          architects: [
            "",
            "",
          ],
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 23,
          name: "",
          image: "",
          yearFounded: ,
          privatOrPublic: "",
          city: "",
          stateOrProvince: "",
          country: "",
          architects: [
            "",
            "",
          ],
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 24,
          name: "",
          image: "",
          yearFounded: ,
          privatOrPublic: "",
          city: "",
          stateOrProvince: "",
          country: "",
          architects: [
            "",
            "",
          ],
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 25,
          name: "",
          image: "",
          yearFounded: ,
          privatOrPublic: "",
          city: "",
          stateOrProvince: "",
          country: "",
          architects: [
            "",
            "",
          ],
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 26,
          name: "",
          image: "",
          yearFounded: ,
          privatOrPublic: "",
          city: "",
          stateOrProvince: "",
          country: "",
          architects: [
            "",
            "",
          ],
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 27,
          name: "",
          image: "",
          yearFounded: ,
          privatOrPublic: "",
          city: "",
          stateOrProvince: "",
          country: "",
          architects: [
            "",
            "",
          ],
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 28,
          name: "",
          image: "",
          yearFounded: ,
          privatOrPublic: "",
          city: "",
          stateOrProvince: "",
          country: "",
          architects: [
            "",
            "",
          ],
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 29,
          name: "",
          image: "",
          yearFounded: ,
          privatOrPublic: "",
          city: "",
          stateOrProvince: "",
          country: "",
          architects: [
            "",
            "",
          ],
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 30,
          name: "",
          image: "",
          yearFounded: ,
          privatOrPublic: "",
          city: "",
          stateOrProvince: "",
          country: "",
          architects: [
            "",
            "",
          ],
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 31,
          name: "",
          image: "",
          yearFounded: ,
          privatOrPublic: "",
          city: "",
          stateOrProvince: "",
          country: "",
          architects: [
            "",
            "",
          ],
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 32,
          name: "",
          image: "",
          yearFounded: ,
          privatOrPublic: "",
          city: "",
          stateOrProvince: "",
          country: "",
          architects: [
            "",
            "",
          ],
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 33,
          name: "",
          image: "",
          yearFounded: ,
          privatOrPublic: "",
          city: "",
          stateOrProvince: "",
          country: "",
          architects: [
            "",
            "",
          ],
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 34,
          name: "",
          image: "",
          yearFounded: ,
          privatOrPublic: "",
          city: "",
          stateOrProvince: "",
          country: "",
          architects: [
            "",
            "",
          ],
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 35,
          name: "",
          image: "",
          yearFounded: ,
          privatOrPublic: "",
          city: "",
          stateOrProvince: "",
          country: "",
          architects: [
            "",
            "",
          ],
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 36,
          name: "",
          image: "",
          yearFounded: ,
          privatOrPublic: "",
          city: "",
          stateOrProvince: "",
          country: "",
          architects: [
            "",
            "",
          ],
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 37,
          name: "",
          image: "",
          yearFounded: ,
          privatOrPublic: "",
          city: "",
          stateOrProvince: "",
          country: "",
          architects: [
            "",
            "",
          ],
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 38,
          name: "",
          image: "",
          yearFounded: ,
          privatOrPublic: "",
          city: "",
          stateOrProvince: "",
          country: "",
          architects: [
            "",
            "",
          ],
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 39,
          name: "",
          image: "",
          yearFounded: ,
          privatOrPublic: "",
          city: "",
          stateOrProvince: "",
          country: "",
          architects: [
            "",
            "",
          ],
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 40,
          name: "",
          image: "",
          yearFounded: ,
          privatOrPublic: "",
          city: "",
          stateOrProvince: "",
          country: "",
          architects: [
            "",
            "",
          ],
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 41,
          name: "",
          image: "",
          yearFounded: ,
          privatOrPublic: "",
          city: "",
          stateOrProvince: "",
          country: "",
          architects: [
            "",
            "",
          ],
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 42,
          name: "",
          image: "",
          yearFounded: ,
          privatOrPublic: "",
          city: "",
          stateOrProvince: "",
          country: "",
          architects: [
            "",
            "",
          ],
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 43,
          name: "",
          image: "",
          yearFounded: ,
          privatOrPublic: "",
          city: "",
          stateOrProvince: "",
          country: "",
          architects: [
            "",
            "",
          ],
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 44,
          name: "",
          image: "",
          yearFounded: ,
          privatOrPublic: "",
          city: "",
          stateOrProvince: "",
          country: "",
          architects: [
            "",
            "",
          ],
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 45,
          name: "",
          image: "",
          yearFounded: ,
          privatOrPublic: "",
          city: "",
          stateOrProvince: "",
          country: "",
          architects: [
            "",
            "",
          ],
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 46,
          name: "",
          image: "",
          yearFounded: ,
          privatOrPublic: "",
          city: "",
          stateOrProvince: "",
          country: "",
          architects: [
            "",
            "",
          ],
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 47,
          name: "",
          image: "",
          yearFounded: ,
          privatOrPublic: "",
          city: "",
          stateOrProvince: "",
          country: "",
          architects: [
            "",
            "",
          ],
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 48,
          name: "",
          image: "",
          yearFounded: ,
          privatOrPublic: "",
          city: "",
          stateOrProvince: "",
          country: "",
          architects: [
            "",
            "",
          ],
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 49,
          name: "",
          image: "",
          yearFounded: ,
          privatOrPublic: "",
          city: "",
          stateOrProvince: "",
          country: "",
          architects: [
            "",
            "",
          ],
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
        {
          ranking: 50,
          name: "",
          image: "",
          yearFounded: ,
          privatOrPublic: "",
          city: "",
          stateOrProvince: "",
          country: "",
          architects: [
            "",
            "",
          ],
          yards: ,
          par: ,
          lat: ,
          lng: ,
          description: "",
        },
      ]);
    });
};
